name: Publish Release
on: 
  push:
    branches: [ main ]
    tags-ignore:
      - '*'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create a Release
      uses: elgohr/Github-Release-Action@main
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
      with:
        title: ${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CR_PAT }} # for pushing to protected branch
      - name: Publish new version
        run: |
          git config --global user.email "frie321984@googlemail.com"
          git config --global user.name "Release Bot"
          git tag -fa v2 -m "Update tag"
          git push origin v2 --force
